// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqqowhsnyzyvcuccujac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxcW93aHNueXp5dmN1Y2N1amFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NzY5NDgsImV4cCI6MjA3MDU1Mjk0OH0.91s8xLdvedfPaf2CO-49kmGaGLb1Y9x4RJIcwUrF4Gc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});